#!/usr/bin/env bash

# echo "verdaccio:$(echo verdaccio | sha1sum | awk '{print $1}')" | base64 > /verdaccio/storage/htpasswd

touch /verdaccio/storage/htpasswd
npm adduser --registry http://localhost:4873
