#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "npmRegistryServer: http://localhost:4873" > ~/.yarnrc.yml
echo "unsafeHttpWhitelist: [\"localhost\"]" >> ~/.yarnrc.yml

yarn npm login