#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# somehow it is an error to request a new token if there is an old one
rm -f ~/.npmrc

node "$SCRIPT_DIR/../dist/verdaccio-openid.mjs" --registry http://localhost:4873

npm config set registry http://localhost:4873